"""Create initial schema

Revision ID: c63c3af3ccab
Revises: 
Create Date: 2023-05-15 16:50:16.542856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63c3af3ccab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drinks_name'), 'drinks', ['name'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('add_drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink_name', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('hot', sa.Boolean(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('size_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drink_name'], ['drinks.name'], ),
    sa.ForeignKeyConstraint(['order_number'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('add_drinks')
    op.drop_table('orders')
    op.drop_index(op.f('ix_drinks_name'), table_name='drinks')
    op.drop_table('drinks')
    # ### end Alembic commands ###
